version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_giraf_local
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/mnt/data:Z
    environment:
      - MINIO_ROOT_USER=girafminio
      - MINIO_ROOT_PASSWORD=girafminio
      - MINIO_VOLUMES=/mnt/data
    command: server /mnt/data --console-address ":9001"

  postgres:
    image: postgres:latest
    container_name: postgres_giraf_local
    restart: unless-stopped
    ports:
      - "7654:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=giraf
      - PGDATA=/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer_giraf_local
    ports:
      - "8000:8080"
