name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Branch info
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to main from stage."
          exit 1
