name: .NET
on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: giraf
        ports:
          - 7654:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Run backend in background
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        WORKSPACE: ${{ secrets.WORKSPACE }}
        DB_HOST: 127.0.0.1
        DB_PORT: 7654
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: giraf
      run: |
        dotnet run --no-build --urls http://localhost:8080 --project FoodplannerApi/FoodplannerApi.csproj &
        echo $! > backend.pid &
        sleep 5

    - name: Generate OpenAPI JSON
      run: curl http://localhost:8080/swagger/v1/swagger.json -o openapi.json

    - name: Upload OpenAPI JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-json
        path: openapi.json

